"""Report generation and markdown viewer for TaskFlow."""

from datetime import datetime
from pathlib import Path

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.table import Table

from taskflow import __app_name__, __version__
from taskflow.config import TaskConfig, TaskStats
from taskflow.progress import format_time


def generate_report(config: TaskConfig, stats: TaskStats) -> str:
    """Generate a markdown report of the task execution."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""# {__app_name__} Execution Report

**Generated:** {timestamp}
**Version:** {__version__}

---

## Configuration

| Parameter | Value |
|-----------|-------|
| Outer Iterations | {config.outer_iterations} |
| Middle Iterations | {config.middle_iterations} |
| Inner Iterations (max) | {config.inner_iterations} |
| Short Circuit Probability | {config.short_circuit_probability:.1%} |

---

## Execution Summary

| Metric | Value |
|--------|-------|
| Total Outer Iterations | {stats.total_outer_iterations} |
| Total Middle Iterations | {stats.total_middle_iterations} |
| Total Inner Iterations | {stats.total_inner_iterations} |
| Short Circuit Events | {stats.short_circuit_count} |
| Total Elapsed Time | {format_time(stats.total_elapsed_seconds)} ({stats.total_elapsed_seconds:.2f}s) |

---

## Performance Analysis

### Iteration Efficiency

- **Expected Inner Iterations:** {config.outer_iterations * config.middle_iterations * config.inner_iterations}
- **Actual Inner Iterations:** {stats.total_inner_iterations}
- **Efficiency:** {(stats.total_inner_iterations / max(1, config.outer_iterations * config.middle_iterations * config.inner_iterations)) * 100:.1f}%

### Short Circuit Rate

- **Total Possible Short Circuits:** {config.outer_iterations * config.middle_iterations}
- **Actual Short Circuits:** {stats.short_circuit_count}
- **Short Circuit Rate:** {(stats.short_circuit_count / max(1, config.outer_iterations * config.middle_iterations)) * 100:.1f}%

---

## Execution Log

```
{chr(10).join(stats.messages)}
```

---

## Notes

- The inner loop may terminate early due to random short-circuiting
- Time measurements include async sleep delays for simulation
- This report was automatically generated by {__app_name__} v{__version__}

---

*Thank you for using {__app_name__}!*
"""
    return report


def save_report(report: str, path: Path) -> None:
    """Save the report to a file."""
    path.write_text(report, encoding="utf-8")


def display_summary(console: Console, config: TaskConfig, stats: TaskStats) -> None:
    """Display a summary of the execution in the console."""
    summary_table = Table(title="Execution Summary", border_style="green")
    summary_table.add_column("Metric", style="cyan")
    summary_table.add_column("Value", style="white")

    summary_table.add_row("Outer Iterations", str(stats.total_outer_iterations))
    summary_table.add_row("Middle Iterations", str(stats.total_middle_iterations))
    summary_table.add_row("Inner Iterations", str(stats.total_inner_iterations))
    summary_table.add_row("Short Circuits", str(stats.short_circuit_count))
    summary_table.add_row("Total Time", format_time(stats.total_elapsed_seconds))

    expected = config.outer_iterations * config.middle_iterations * config.inner_iterations
    efficiency = (stats.total_inner_iterations / max(1, expected)) * 100

    summary_table.add_row("Efficiency", f"{efficiency:.1f}%")

    console.print()
    console.print(Panel(summary_table, border_style="bright_green"))
    console.print()


def view_report_interactive(console: Console, report_path: Path) -> None:
    """
    Display the markdown report in an interactive viewer.

    Uses Rich's built-in pager for scrolling.
    """
    if not report_path.exists():
        console.print(f"[red]Error:[/red] Report file not found: {report_path}")
        return

    content = report_path.read_text(encoding="utf-8")
    md = Markdown(content)

    console.print()
    console.print(
        Panel(
            "[dim]Use arrow keys or Page Up/Down to scroll. Press 'q' to quit.[/dim]",
            border_style="dim",
        )
    )
    console.print()

    # Use Rich's pager for interactive viewing
    with console.pager(styles=True):
        console.print(md)
